### PR TITLE
Add documentation for e2e-flow sample usecase

### PR DESCRIPTION
**Pull request by Akash-Nayak**
Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

### CODE REVIEW

**Comment by Akash-Nayak** [comment]
The added documentation can be viewed at https://akash-nayak.github.io/move2kube/tutorials/e2e-flow/.

**Comment by ashokponkumar** [comment]
@Akash-Nayak Is there a way to have the terminal ui as text while visually similar to the terminal output? If we add a lot of images, the repo size willl increase quite a bit. 

Are you aware of any such formatting tool for markdown?

**Comment by Akash-Nayak** [comment]
> @Akash-Nayak Is there a way to have the terminal ui as text while visually similar to the terminal output? If we add a lot of images, the repo size willl increase quite a bit.
> 
> Are you aware of any such formatting tool for markdown?

Yes sure, adding too many images will definitely increase the repo size and make the loading of webpage slow, as there are more demos to be added as well. I am not aware of such formatting tool for markdown but will check for it.

**Comment by Akash-Nayak** [comment]
> > @Akash-Nayak Is there a way to have the terminal ui as text while visually similar to the terminal output? If we add a lot of images, the repo size willl increase quite a bit.
> > Are you aware of any such formatting tool for markdown?
> 
> Yes sure, adding too many images will definitely increase the repo size and make the loading of webpage slow, as there are more demos to be added as well. I am not aware of such formatting tool for markdown but will check for it.

I have made some changes in the documentation. 
* Updated the Prerequisites: Updated move2kube installation command, added the steps to install the dependencies including the installation through installdeps.sh, and added Helm v3 in the dependencies.
* Removed all the images of the terminal output and added text in place of it.
* Added the steps (in form of ordered list) for deployment to K8s cluster.
* For running pushimages.sh, specified the requirement of login to the docker registry.

**Review by ashokponkumar — APPROVED** [review]

**Pull request merged**
