### PR TITLE
fix: categorize QA engine questions

### PR DESCRIPTION
**Pull request by Soumil-07**
Categorizes QA questions as defined by a new mappings file. Adds two flags: --qa-enable and --qa-disable for finer grained control

### CODE REVIEW

**Comment by Akash-Nayak** [comment]
Hi @Soumil-07, last week while you were demoing the categorizing QA feature I think we had found a bug- when categories were specified in a new question in custom starlark-based transformer and they were not getting reflected during the QA in transform phase, and it was still showing as `external` category. Were you able to fix that bug? 

Screenshot 2023-11-02 at 3 04 16 PM

**Comment by Soumil-07** [comment]
> Hi @Soumil-07, last week while you were demoing the categorizing QA feature I think we had found a bug- when categories were specified in a new question in custom starlark-based transformer and they were not getting reflected during the QA in transform phase, and it was still showing as `external` category. Were you able to fix that bug?
> 
> Screenshot 2023-11-02 at 3 04 16 PM

Hi! Apparently it wasn't a bug, I was using the wrong attribute during our demo (I used `category`, it should be `categories`). Passing the correct, attribute it properly categorizes the question according to the specified categories. 

image

**Review by Akash-Nayak — APPROVED** [review]
LGTM

**Comment by Akash-Nayak** [comment]
@Soumil-07 can you rebase this branch as it is out-of-date with the main branch.

**Review by HarikrishnanBalagopal — APPROVED** [review]
rebased automatically on Github

**Comment by HarikrishnanBalagopal** [comment]
Related https://github.com/konveyor/move2kube/issues/861

**Pull request merged**
