### PR TITLE
fix: Fix to enable health check on admin port from operator deployment

### PR DESCRIPTION
**Pull request by deewhyweb**
Containers deployed by the wildfly operator need to respond to health checks on port 9090, to do this the admin interface needs to be configured to accept connections from ips other than localhost.

### CODE REVIEW

**Review by ashokponkumar — APPROVED** [review]

**Comment by ashokponkumar** [comment]
Thanks for the PR. Can you please sign off the commit (https://github.com/konveyor/move2kube/pull/917/checks?check_run_id=9756286624) and then we can merge this PR.

**Comment by HarikrishnanBalagopal** [comment]
> Containers deployed by the wildfly operator need to respond to health checks on port 9090, to do this the admin interface needs to be configured to accept connections from ips other than localhost.

```
connections from ips other than localhost.
```
My understanding is that this is to prevent attacks from outside the cluster. Usually you create a proxy pod inside the cluster and access the admin console via that.

**Comment by HarikrishnanBalagopal** [comment]
> Containers deployed by the wildfly operator need to respond to health checks on port 9090, to do this the admin interface needs to be configured to accept connections from ips other than localhost.

We can go ahead with this if you find it fits with the conventions.

**Comment by deewhyweb** [comment]
When we build EAP images for OpenShift using S2I the admin console is disabled, the reason being that configuration changes should be performed by script rather than via the cli or admin console.  https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index

**Comment by ashokponkumar** [comment]
> https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index

@deewhyweb Is this fix still required? If so, can you please fix the DCO (you will need to [signoff](https://github.com/konveyor/move2kube/pull/917/checks?check_run_id=9756286624) the commit), and then we can merge.

**Comment by deewhyweb** [comment]
I'm away from my machine for the next few hours, will fix the DCO when I get back online.

**Comment by deewhyweb** [comment]
Not sure why this check is still failing, as far as I can see the commit has been signed

**Comment by ashokponkumar** [comment]
> Not sure why this check is still failing, as far as I can see the commit has been signed

Have manually set DCO to pass. Thanks!

**Pull request merged**
