### PR TITLE
fix: replace deprecated ioutil readfile function

### PR DESCRIPTION
**Pull request by SVKREP**
Replace  ioutil.Readfile -> os.Readfile. As it is deprecated from go v1.16.

### CODE REVIEW

**Comment by seshapad** [comment]
@SVKREP Why is an entire function being replaced to handle a deprecation?

**Review by HarikrishnanBalagopal — APPROVED** [review]
LGTM

**Comment by HarikrishnanBalagopal** [comment]
> @SVKREP Why is an entire function being replaced to handle a deprecation?

I think it's just removing spaces at the beginning unless I am mistaken

**Comment by HarikrishnanBalagopal** [comment]
@SVKREP can you fetch the latest `main` and rebase your commits on top of that? There are some merge conflicts.

**Comment by Akash-Nayak** [comment]
@SVKREP There are some merge conflicts that are required to be resolved, so that we can merge the PR. Can you please rebase the branch (https://github.com/konveyor/move2kube/blob/main/contributing.md#pull-request-process) and resolve the merge conflicts.

**Comment by SVKREP** [comment]
Hi Team, Merge conflicts are fixed, please LTM if you need me do any other changes!

**Review by kmehant — APPROVED** [review]
LGTM

**Pull request merged**
