### PR TITLE
fix: crashes when pom file build section is absent

### PR DESCRIPTION
**Pull request by seshapad**
Signed-off-by: Padmanabha V Seshadri <seshapad@in.ibm.com>

### CODE REVIEW

**Review by HarikrishnanBalagopal — CHANGES_REQUESTED** [review]
Can you add the same nil check here? https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/mavenanalyser.go#L612

**Comment by HarikrishnanBalagopal** [comment]
@seshapad also here https://github.com/konveyor/move2kube/blob/main/types/source/maven/pom.go#L85

```
	if pom.Properties.Entries == nil {
		return "", fmt.Errorf("property not found in pom")
	}
```

**Comment by seshapad** [comment]
> Can you add the same nil check here? https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/mavenanalyser.go#L612

done!

**Comment by HarikrishnanBalagopal** [comment]
@seshapad and here https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/mavenanalyser.go#L632-L633

**Comment by seshapad** [comment]
> @seshapad and here https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/mavenanalyser.go#L632-L633

Done!

**Comment by seshapad** [comment]
> @seshapad and here https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/mavenanalyser.go#L632-L633

done!

**Comment by seshapad** [comment]
> @seshapad also here https://github.com/konveyor/move2kube/blob/main/types/source/maven/pom.go#L85
> 
> ```
> 	if pom.Properties == nil || pom.Properties.Entries == nil {
> 		return "", fmt.Errorf("property not found in pom")
> 	}
> ```

Done!

**Comment by HarikrishnanBalagopal** [comment]
@seshapad a few places in gradleanalyzer too https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/gradleanalyser.go#L759
```
if len(gbb.Metadata != nil && len(gbb.Metadata[languageVersionC]) > 0 {
```

**Comment by seshapad** [comment]
> @seshapad a few places in gradleanalyzer too
> 
>     1. https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/gradleanalyser.go#L759
> 
> 
> ```
> if gbb.Metadata != nil && len(gbb.Metadata[languageVersionC]) > 0 {
> ```
> 
>     2. https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/gradleanalyser.go#L772
> 
>     3. https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/gradleanalyser.go#L816
> 
>     4. https://github.com/konveyor/move2kube/blob/main/transformer/dockerfilegenerator/java/gradleanalyser.go#L757

Done!

**Review by HarikrishnanBalagopal — APPROVED** [review]
Thanks @seshapad . The nil checks should work for now but we will probably need to revisit this since the semantics may not be correct.

**Pull request merged**
