### PR TITLE
fix: key error from detect for operatorsfromtca transformer

### PR DESCRIPTION
**Pull request by ChillOrb**
Fixing error in https://github.com/konveyor/move2kube/issues/1079

### CODE REVIEW

**Comment by kmehant** [comment]
Thanks for the PR @ChillOrb 
Can you please follow the PR labeling convention from here - https://github.com/konveyor/move2kube/blob/main/contributing.md#pull-request-process
I assume renaming PR to `fix: key error from detect for operatorsfromtca transformer`

**Comment by ChillOrb** [comment]
> Thanks for the PR @ChillOrb
> Can you please follow the PR labeling convention from here - https://github.com/konveyor/move2kube/blob/main/contributing.md#pull-request-process
> I assume renaming PR to `fix: key error from detect for operatorsfromtca transformer`

@kmehant Thanks for the reply. Fixed it

**Comment by kmehant** [comment]
@ChillOrb you would need to sign your commits. https://github.com/konveyor/move2kube/blob/main/contributing.md#sign-your-commits

Thanks.

**Review by HarikrishnanBalagopal — APPROVED** [review]
LGTM

**Comment by HarikrishnanBalagopal** [comment]
@ChillOrb Hi, Thanks for the fix.

Can you please sign off on the commit so the DCO check can pass?

**Comment by ChillOrb** [comment]
@kmehant @HarikrishnanBalagopal Done , thanks for review. Will remember to sign next time.

**Comment by HarikrishnanBalagopal** [comment]
> @kmehant @HarikrishnanBalagopal Done , thanks for review. Will remember to sign next time.

Thanks

**Pull request merged**
