### PR TITLE
fix: binaries compressed for Ubuntu seg fault when run on CentOS

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

### CODE REVIEW

**Comment by ashokponkumar** [comment]
Was thinking we can remove the entire upx stuff from our code, including Makefiles. Anyway, we use zip for our releases, so it should compress reducing the download. 

Thoughts?

**Comment by HarikrishnanBalagopal** [comment]
> Was thinking we can remove the entire upx stuff from our code, including Makefiles. Anyway, we use zip for our releases, so it should compress reducing the download.
> 
> Thoughts?

It doesn't hurt to have it. Still works when you are compiling locally.

**Comment by ashokponkumar** [comment]
The main benefit was network download speed, which is anyway optimised by the archive format. 

If upx is present locally, our makefile will start using it. We won't know the version of upx and it might cause errors and there is no real benefit to them if built locally, since a 40 MB addition is not big for a hard disk. Also, I would assume compressing will increase execution time at least by a bit.

**Comment by HarikrishnanBalagopal** [comment]
> If upx is present locally, our makefile will start using it.

Yeah and that's fine because it works locally

**Comment by HarikrishnanBalagopal** [comment]
> The main benefit was network download speed, which is anyway optimised by the archive format.
> 
> If upx is present locally, our makefile will start using it. We won't know the version of upx and it might cause errors and there is no real benefit to them if built locally, since a 40 MB addition is not big for a hard disk. Also, I would assume compressing will increase execution time at least by a bit.

I have removed it entirely.

**Review by ashokponkumar — APPROVED** [review]

**Pull request merged**
