### PR TITLE
fix: javamaven dockerfile template change

### PR DESCRIPTION
**Pull request by alealavi**
app folder was not being created, image was changed for openjdk 1.8 and works, only needed is change the .app_name to be the same as the current project name being translated

### CODE REVIEW

**Review by HarikrishnanBalagopal — DISMISSED** [review]
Need to run `make generate` for this change to have any effect.

The original issue may have been because of some other reason.

**Comment by alealavi** [comment]
you were right it was probably a permissions problem since now it works without having to make the app folder, however I still get a jboss error if I leave the image, so Im leaving that change but reverted the "mkdir app" one

I also signed off the changes this time so the checks all pass and generated a new constants file

The jboss error should be below if you want to see it, but with the image change now it works

image

**Comment by HarikrishnanBalagopal** [comment]
Sure, the base image change seems fine.

Thanks for making the changes!

**Review by HarikrishnanBalagopal — APPROVED** [review]
LGTM

**Pull request merged**
