### PR TITLE
Add ruby support for the default dockerfile containerizers

### PR DESCRIPTION
**Pull request by akhil-ghatiki**
This addresses the https://github.com/konveyor/move2kube/issues/26 issue. 
This commit adds support for Ruby in the default dockerfile containerizers.
Followed all the required steps mentioned in the issue.

- [x] `make generate` - The commit has the generated files required.

- [x] `make build` - The build was successful.

- [x] `move2kube translate -s srcfolder` - Tested with a simple ruby application and move2kube was able to detect it successfully. (Adding the screen shot below for reference)

m2k translate

### CODE REVIEW

**Comment by ashokponkumar** [comment]
Thanks @akhil-ghatiki for the PR. Much appreciate it. Please feel free to make more PRs as might be appropriate.

**Comment by akhil-ghatiki** [comment]
@ashokponkumar I don't exactly understand why this build failed. There are not logs for the failure in details. Can you give me any inputs on this ?

**Comment by ashokponkumar** [comment]
You can check it out in https://travis-ci.com/github/konveyor/move2kube/builds/189306775. It is essentially failing because `make test-style` is failing. `make test-style` is failing because of missing license headers.

If you can add the license headers to the files you added, and did a `make test-style`, and if it succeeds, the build will succeed.

**Comment by akhil-ghatiki** [comment]
> You can check it out in https://travis-ci.com/github/konveyor/move2kube/builds/189306775. It is essentially failing because `make test-style` is failing. `make test-style` is failing because of missing license headers.
> 
> If you can add the license headers to the files you added, and did a `make test-style`, and if it succeeds, the build will succeed.

Thanks @ashokponkumar. I think we can `make test-style` as part of build script. We can fail the local build if `make-test` fails. What's your opinion on this ?

**Comment by ashokponkumar** [comment]
> > You can check it out in https://travis-ci.com/github/konveyor/move2kube/builds/189306775. It is essentially failing because `make test-style` is failing. `make test-style` is failing because of missing license headers.
> > If you can add the license headers to the files you added, and did a `make test-style`, and if it succeeds, the build will succeed.
> 
> Thanks @ashokponkumar. Fixed it. Also, I think we can `make test-style` as part of build script. We can fail the local build if `make-test` fails. What's your opinion on this ?

Thanks for the suggestion @akhil-ghatiki . I agree, have created a new issue https://github.com/konveyor/move2kube/issues/51 based on your comment.

**Pull request merged**
