### PR TITLE
fix: remove external transformer temp directories on interrupt

### PR DESCRIPTION
**Pull request by kmehant**
Signed-off-by: Mehant Kammakomati <mehant.kammakomati2@ibm.com>

### CODE REVIEW

**Comment by ashokponkumar** [comment]
@seshapad are these paths used inside the container or external to them?

**Comment by kmehant** [comment]
Screenshot 2023-04-10 at 11 01 00 PM

@ashokponkumar @seshapad they are used externally.

**Comment by ashokponkumar** [comment]
Hmm.. how does it work in windows then.. there might be a larger issue in play here then..

**Comment by kmehant** [comment]
https://github.com/konveyor/move2kube/blob/73ab28607a7350ce5b75cc3afcfb6487eb059d3d/environment/local.go#L139-L156

this function seems to do this. 

@seshapad can confirm.

**Comment by kmehant** [comment]
@ashokponkumar https://github.com/konveyor/move2kube/pull/1019#issuecomment-1502094717

Yes, there should be a drive and the way paths are joined would different.

**Comment by seshapad** [comment]
> @seshapad are these paths used inside the container or external to them?

Yes @ashokponkumar . It's meant to let configure the external transformer on where to pick input and where to write output.

**Pull request merged**
