### PR TITLE
docs: add instructions for setting an alias for the `move2kube` command in the shell

### PR DESCRIPTION
**Pull request by Sanket-0510**
as discussed here #1135 I feel there is a strong need to address, its all okay if we can't change it during installation but shall surely have section to address the same. Because writing 'move2kube' becomes a tedious task for sure.

### CODE REVIEW

**Comment by KrishAryan** [comment]
@Sanket-0510 I think you forgot to sign your commit.

To fix this please [read:](https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/contributors/signing-commits.html#:~:text=If%20you%20need%20to%20re,%2D%2Dno%2Dedit%20%2Ds%20.)

**Comment by Sanket-0510** [comment]
> @Sanket-0510 I think you forgot to sign your commit.
> 
> To fix this please read [this](https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/contributors/signing-commits.html#:~:text=If%20you%20need%20to%20re,%2D%2Dno%2Dedit%20%2Ds%20.)
> 
> Also please read the [contribution.md](https://github.com/konveyor/move2kube/blob/main/contributing.md)

Hey @KrishAryan you can review this.

**Comment by KrishAryan** [comment]
@Sanket-0510 I think it would look better if you write 'To keep aliases between sessions, you can save them in your user’s shell configuration profile file' and give the example of only bash script otherwise the readme will look unnecessarily long. I am not a maintainer so I cannot approve this for you but wanted to help save their time.

**Comment by Sanket-0510** [comment]
> @Sanket-0510 I think it would look better if you write 'To keep aliases between sessions, you can save them in your user’s shell configuration profile file' and give the example of only bash script otherwise the readme will look unnecessarily long. I am not a maintainer so I cannot approve this for you but wanted to help save their time.

will you please highlight in the code, the exact place

**Review by KrishAryan — CHANGES_REQUESTED** [review]
between line 127 and line 129 you can add the comment and remove zsh and fish section.Also use three hashags in line 127 instead of two so that it can look better. 

Also in your second commit which is in go.mod file, why did you do the changes in line 22 and removed line 119

**Comment by Sanket-0510** [comment]
> between line 127 and line 129 you can add the comment and remove zsh and fish section.Also use three hashags in line 127 instead of two so that it can look better.
> 
> Also in your second commit which is in go.mod file, why did you do the changes in line 22 and removed line 119

Hey, actually, it's the Go package manager, I guess, which made the changes. I didn't explicitly change it, and the build is successful on my side

**Comment by KrishAryan** [comment]
@kmehant can you please review and approve it?

**Review by HarikrishnanBalagopal — APPROVED** [review]
LGTM

**Review by kmehant — APPROVED** [review]

**Pull request merged**
